services:
  db:
    image: postgres:17-alpine
    container_name: my-database
    env_file:
      - ./.prod.env
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - my-network

  backend:
    container_name: my-backend
    build:
      context: .
    env_file:
      - ./.prod.env
    networks:
      - my-network
    depends_on:
      - db

  nginx:
    container_name: my-reverse-proxy
    build:
      context: ./front
    ports:
      - 3001:3001
    networks:
      - my-network
    volumes:
      - ./front/templates:/etc/nginx/templates:ro
    depends_on:
      - db
      - backend


volumes:
  db-volume:

networks:
  my-network:
