services:
  db:
    image: postgres:17-alpine
    container_name: my-database
    env_file:
      - ./.prod.env
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - my-network

  backend:
    container_name: my-backend
    build:
      context: .
    env_file:
      - ./.prod.env
    networks:
      - my-network
    depends_on:
      - db

  nginx:
    container_name: my-reverse-proxy
    build:
      context: ./front
    ports:
      - ${NGINX_PORT:-3000}:${NGINX_PORT:-3000}
    networks:
      - my-network
    extra_hosts:
      - "host:host-gateway"
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    volumes:
      - ./front/nginx_template:/etc/nginx/templates:ro
      - ${LETSENCRYPT_DIR:-/etc/letsencrypt}:/etc/letsencrypt:ro
    depends_on:
      - db
      - backend


volumes:
  db-volume:

networks:
  my-network:
