services:
  db:
    image: dhi.io/postgres:18-alpine3.23-dev
    container_name: database-only
    env_file:
      - ./.prod.env
    ports:
      - 4444:5432
    volumes:
      - db-volume:/var/lib/postgresql/18/data

volumes:
  db-volume:

